import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "~/styles/Home.module.css";
import * as bitcoin from "bitcoinjs-lib";
import * as ecc from "tiny-secp256k1";
import { useEffect, useState } from "react";
bitcoin.initEccLib(ecc);

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [message, setMessage] = useState("Loading...");
  useEffect(() => {
    setTimeout(() => {
      setMessage("Happy");
    }, 5000);
  }, []);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>Bitcoin {message}</main>
    </>
  );
}
